# Generated by Django 6.0.6 on 2026-08-07 11:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scrap', '0013_receivedscrap_unique_received_scrap_per_department_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_kg', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Scrap.department')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Scrap.sku')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Waste.wasteunits')),
            ],
        ),
        migrations.CreateModel(
            name='ActualWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_kg', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Scrap.department')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Scrap.sku')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Waste.wasteunits')),
            ],
        ),
    ]
