# Generated by Django 6.0.6 on 2026-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0013_receivedscrap_unique_received_scrap_per_department_date'),
        ('Waste', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receivedwaste',
            constraint=models.UniqueConstraint(fields=('department', 'date'), name='unique_received_waste_department_date'),
        ),
    ]
