# Generated by Django 6.0.6 on 2026-08-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Waste', '0002_receivedwaste_unique_received_waste_department_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualwaste',
            name='nb_of_units',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receivedwaste',
            name='nb_of_units',
            field=models.IntegerField(default=1),
        ),
    ]
