# Generated by Django 6.0.6 on 2026-08-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Waste', '0003_actualwaste_nb_of_units_receivedwaste_nb_of_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualwaste',
            name='nb_of_units',
        ),
        migrations.RemoveField(
            model_name='actualwaste',
            name='units',
        ),
        migrations.CreateModel(
            name='ActualWasteUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_of_units', models.PositiveIntegerField(default=1)),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Waste.wasteunits')),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_lines', to='Waste.actualwaste')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('waste', 'units'), name='unique_actual_waste_unit')],
            },
        ),
    ]
