# Generated by Django 6.0.6 on 2026-08-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Waste', '0005_remove_receivedwaste_nb_of_units_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='receivedwaste',
            name='unique_received_waste_department_date',
        ),
    ]
