# Generated by Django 6.0.6 on 2026-08-10 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0013_receivedscrap_unique_received_scrap_per_department_date'),
        ('Waste', '0006_remove_receivedwaste_unique_received_waste_department_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actualwasteunit',
            name='unique_actual_waste_unit',
        ),
        migrations.RemoveConstraint(
            model_name='receivedwasteunit',
            name='unique_received_waste_unit',
        ),
        migrations.RemoveField(
            model_name='actualwaste',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='receivedwaste',
            name='sku',
        ),
        migrations.AddField(
            model_name='actualwasteunit',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Scrap.sku'),
        ),
        migrations.AddField(
            model_name='receivedwasteunit',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Scrap.sku'),
        ),
        migrations.AddConstraint(
            model_name='actualwasteunit',
            constraint=models.UniqueConstraint(fields=('waste', 'sku', 'units'), name='unique_actual_waste_unit'),
        ),
        migrations.AddConstraint(
            model_name='receivedwasteunit',
            constraint=models.UniqueConstraint(fields=('waste', 'sku', 'units'), name='unique_received_waste_unit'),
        ),
    ]
