# Generated by Django 6.0.6 on 2026-10-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Waste', '0007_remove_actualwasteunit_unique_actual_waste_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='actualwasteunit',
            name='serial_number',
            field=models.TextField(blank=True, help_text='Fill in only if this is a complete cylinder.', verbose_name='Serial number (if complete cylinder)'),
        ),
        migrations.AddField(
            model_name='receivedwasteunit',
            name='serial_number',
            field=models.TextField(blank=True, help_text='Fill in only if this is a complete cylinder.', verbose_name='Serial number (if complete cylinder)'),
        ),
        migrations.AddField(
            model_name='actualwasteunit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actual_waste_units', to='Waste.project'),
        ),
        migrations.AddField(
            model_name='receivedwasteunit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_waste_units', to='Waste.project'),
        ),
    ]
