# Generated by Django 6.0.6 on 2026-10-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0016_alter_actualscrap_options_and_more'),
        ('Waste', '0008_project_actualwasteunit_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actualwasteunit',
            name='unique_actual_waste_unit',
        ),
        migrations.AddConstraint(
            model_name='actualwasteunit',
            constraint=models.UniqueConstraint(fields=('waste', 'sku', 'units', 'project'), name='unique_actual_waste_unit'),
        ),
    ]
