# Generated by Django 6.0.6 on 2026-10-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0016_alter_actualscrap_options_and_more'),
        ('Waste', '0009_remove_actualwasteunit_unique_actual_waste_unit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='receivedwasteunit',
            name='unique_received_waste_unit',
        ),
        migrations.AddConstraint(
            model_name='receivedwasteunit',
            constraint=models.UniqueConstraint(fields=('waste', 'sku', 'units', 'project'), name='unique_received_waste_unit'),
        ),
    ]
