# Generated by Django 6.0.6 on 2026-08-03 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calculation_type', models.CharField(choices=[('KG', 'Steel Used'), ('UNITS', 'Units Produced')], max_length=10)),
                ('uses_size', models.BooleanField(default=True)),
                ('uses_thickness', models.BooleanField(default=False)),
                ('uses_diameter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('steel_used_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('units_produced', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Scrap.department')),
            ],
            options={
                'ordering': ['-production_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActualScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_scrap_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('production_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actual_scrap', to='Scrap.productionentry')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('scrap_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Scrap.department')),
            ],
            options={
                'unique_together': {('department', 'size', 'thickness', 'diameter')},
            },
        ),
    ]
