# Generated by Django 6.0.6 on 2026-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapstandard',
            name='active',
        ),
        migrations.AlterField(
            model_name='actualscrap',
            name='entered_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
