# Generated by Django 6.0.6 on 2026-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0002_remove_scrapstandard_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualscrap',
            name='entered_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='created_at',
            field=models.DateField(),
        ),
    ]
