# Generated by Django 6.0.6 on 2026-08-04 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0003_alter_actualscrap_entered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualscrap',
            name='production_entry',
        ),
        migrations.AddField(
            model_name='actualscrap',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Scrap.department'),
        ),
    ]
