# Generated by Django 6.0.6 on 2026-08-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0004_remove_actualscrap_production_entry_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actualscrap',
            constraint=models.UniqueConstraint(fields=('department', 'entered_at'), name='unique_actual_scrap_per_department_date'),
        ),
    ]
