# Generated by Django 6.0.6 on 2026-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0005_actualscrap_unique_actual_scrap_per_department_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='productionentry',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='scrapstandard',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
