# Generated by Django 6.0.6 on 2026-08-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0006_alter_productionentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_number', models.CharField(max_length=100, unique=True)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=6)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='productionentry',
            name='diameter',
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='coil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Scrap.coil'),
        ),
    ]
