# Generated by Django 6.0.6 on 2026-08-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0007_coil_remove_productionentry_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionentry',
            name='coil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Scrap.coil'),
        ),
    ]
