# Generated by Django 6.0.6 on 2026-08-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0008_alter_productionentry_coil'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actualscrap',
            name='unique_actual_scrap_per_department_date',
        ),
        migrations.AddField(
            model_name='actualscrap',
            name='coil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Scrap.coil'),
        ),
        migrations.AlterField(
            model_name='actualscrap',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Scrap.department'),
        ),
        migrations.AddConstraint(
            model_name='productionentry',
            constraint=models.UniqueConstraint(condition=models.Q(('coil__isnull', True), ('size__isnull', False), ('thickness__isnull', False)), fields=('department', 'production_date', 'size', 'thickness'), name='unique_production_trimming'),
        ),
        migrations.AddConstraint(
            model_name='productionentry',
            constraint=models.UniqueConstraint(condition=models.Q(('coil__isnull', True), ('size__isnull', False), ('thickness__isnull', True)), fields=('department', 'production_date', 'size'), name='unique_production_by_size'),
        ),
    ]
