# Generated by Django 6.0.6 on 2026-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0009_remove_actualscrap_unique_actual_scrap_per_department_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualscrap',
            name='actual_scrap_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
