# Generated by Django 6.0.6 on 2026-08-06 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0011_sku_alter_productionentry_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('received_scrap_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Scrap.department')),
            ],
        ),
    ]
