# Generated by Django 6.0.6 on 2026-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0012_receivedscrap'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receivedscrap',
            constraint=models.UniqueConstraint(fields=('department', 'date'), name='unique_received_scrap_per_department_date'),
        ),
    ]
