# Generated by Django 6.0.6 on 2026-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0013_receivedscrap_unique_received_scrap_per_department_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='calculation_type',
            field=models.CharField(blank=True, choices=[('KG', 'Steel Used'), ('UNITS', 'Units Produced')], max_length=10, null=True),
        ),
    ]
