# Generated by Django 6.0.6 on 2026-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0014_alter_department_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='skus', to='Scrap.department'),
        ),
    ]
