# Generated by Django 6.0.6 on 2026-10-05 13:17

import Scrap.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0015_sku_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualscrap',
            options={'ordering': ['-entered_at', '-entered_time']},
        ),
        migrations.AlterModelOptions(
            name='receivedscrap',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RemoveConstraint(
            model_name='receivedscrap',
            name='unique_received_scrap_per_department_date',
        ),
        migrations.AddField(
            model_name='actualscrap',
            name='entered_time',
            field=models.TimeField(default=Scrap.models.current_time),
        ),
        migrations.AddField(
            model_name='receivedscrap',
            name='time',
            field=models.TimeField(default=Scrap.models.current_time),
        ),
        migrations.AlterField(
            model_name='actualscrap',
            name='entered_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='receivedscrap',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
